apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: devops
        ports:
        - containerPort: 80
